pipeline {
    agent {
        node {
            label 'built-in'
            // Evita colisiones definiendo una ruta fija y aislada
            customWorkspace "/var/jenkins_home/workspace/web-app-feature-check"
        }
    }
    stages {
        stage('Static Analysis') {
            steps {
                script {
                    def scannerHome = tool 'sonar-scanner'
                    withSonarQubeEnv('sonarqube') {
                        sh "${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=web-app-feature \
                        -Dsonar.sources=."
                    }
                }
            }
        }
    }
}
